language: go

git:
  depth: false

env:
  global:
    - CACHE_NAME=${TRAVIS_ARCH}
    - GO111MODULE=on
    - GOPROXY=https://proxy.golang.org
    - HUGO_BUILD_TAGS=extended

install:
  - go get github.com/sourcegraph/lsif-go/cmd/lsif-go
  - curl -L https://github.com/sourcegraph/src-cli/releases/download/3.16.0/src_linux_amd64 -o ./src
  - chmod +x ./src

jobs:
  include:
    - name: Index and upload LSIF data to sourcegraph.com
      os: linux
      go: 1.14.x
      script:
        - lsif-go
        - ./src lsif upload -no-progress
